project:
  type: book
  output-dir: _book # Matches bookdown's default output directory
 
  
book:
  title: "S&DS 3610 Notes"
  author: "Brian Macdonald"
  date: "10/22/2025"
  page-navigation: true
  search: 
    location: sidebar
    type: textbox
    show-item-context: true
  repo-url: https://github.com/bmacgtpm/notes/
  repo-actions: [edit, issue, source]
  sharing: [twitter, linkedin, facebook]
  page-footer: 
    left: 
      - icon: github
        href: https://github.com/bmacgtpm
      - icon: twitter 
        href: https://twitter.com/bmacgtpm 
    center: "© 2025 Brian Macdonald"
    right: "S&DS 3610 Notes"
    background: light
  
  # Link to edit this page
  # edit:
  #   link: "https://github.com/bmacgtpm/notes/edit/main/{{< file-path >}}"

  # header and footer of sidebar: 
  # '2' means chapters are collapsible.
  sidebar: 
    collapse-level: 4
  # doi: 
  # annote #

  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
        - example1.qmd
        - example2.qmd
    - part: "Part 2"
      chapters: 
        - example3.qmd
        - summary.qmd

  appendices:
    - references.qmd
  
toc-depth: 4
number-depth: 4
format:
  closeread-html:
    theme:
      light: cosmo #,  cerulean, spacelab
      dark: darkly #, slate
    css:
      - styles.scss
    respect-user-color-scheme: true
    toc: true
    toc-location: left
    toc-depth: 4
    keyboard-navigation: true
    include-in-header: header.html
    code-fold: true
  
execute:
  freeze: auto
  execute:
  echo: true      # show or suppress the code
  include: true   # show or suppress the output
  message: false  # omit messages generated by code
  warning: false  # omit warnings generated by code
  comment: "NA"   # removes the ## from in front of outputs
  error: false    # stop on errors
  results: "hold" # wait to print results until after the code chunk
  cache: true
  fig-align: "center"
  fig-height: 5
  fig-width: 5 

comments:
  hypothesis: true
